import Link from "next/link";

export default function TermsOfUse() {
  return (
    <div className="min-h-screen bg-[#111] text-white flex flex-col">
      {/* Navigation */}
      <nav className="p-6">
        <div className="flex items-center justify-between max-w-6xl mx-auto">
          <Link href="/" className="flex items-center gap-2">
            <span className="text-xl font-bold">Moodi</span>
          </Link>
        </div>
      </nav>

      {/* Content */}
      <div className="flex-grow max-w-4xl mx-auto px-6 py-12">
        <h1 className="text-4xl font-bold mb-4">EULA For Moodi</h1>
        <p className="text-gray-400 italic mb-8">Last Update: May 17, 2025</p>
        
        <div className="space-y-8 text-gray-300">
          <p className="text-lg">By using the Moodi app, you agree to the following terms:</p>

          <div className="space-y-6">
            <div className="flex gap-4">
              <span className="text-teal-500">1.</span>
              <p>Moodi is provided as-is, with no guarantee of accuracy or fitness for a particular purpose.</p>
            </div>

            <div className="flex gap-4">
              <span className="text-teal-500">2.</span>
              <p>All room designs generated by the app are for visualization purposes only and are not professional architectural plans.</p>
            </div>

            <div className="flex gap-4">
              <span className="text-teal-500">3.</span>
              <p>You retain ownership of any images you upload to the app. Moodi does not claim ownership or rights to your images.</p>
            </div>

            <div className="flex gap-4">
              <span className="text-teal-500">4.</span>
              <p>You may not use the app for any illegal or abusive purpose.</p>
            </div>

            <div className="flex gap-4">
              <span className="text-teal-500">5.</span>
              <p>Moodi reserves the right to modify or discontinue the service at any time without notice.</p>
            </div>
          </div>

          <div className="space-y-4 mt-12">
            <p>These terms may be updated occasionally. Continued use of the app indicates your acceptance of the current terms.</p>
            
            <p>If you have any questions about these terms, please contact support@moodiapp.com.</p>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="px-6 py-10 bg-[#1a1a1a] mt-auto">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row justify-between items-center gap-4">
          <div className="flex items-center gap-2">
            <Link href="/" className="font-bold hover:text-blue-500">
              Moodi
            </Link>
          </div>
          <div className="flex gap-6">
            <Link href="/privacy-policy" className="text-gray-400 hover:text-white">
              Privacy Policy
            </Link>
            <Link href="/terms" className="text-gray-400 hover:text-white">
              EULA
            </Link>
            <Link href="/contact" className="text-gray-400 hover:text-white">
              Contact
            </Link>
          </div>
          <p className="text-gray-400">© 2025 Moodi. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
} 
